baseurl = "https://0xAX.github.io"
languageCode = "en-us"
title = "Just a memo"
newContentEditor = "emacs"
theme = "purehugo"
pygmentsStyle = "native"
draft = false
Paginate = 10

[params]
  twitterName = "0xAX"
  githubName = "0xAX"
  description = "Just a memo"